import { Router } from 'express';
import { authenticate, authorize } from '../../middleware/auth';
import { getBanners, adminGetAllBanners, createBanner, updateBanner, deleteBanner } from './banners.controller';
const router = Router();
router.get('/', getBanners);
router.get('/admin/all', authenticate, authorize('ADMIN'), adminGetAllBanners);
router.post('/', authenticate, authorize('ADMIN'), createBanner);
router.put('/:id', authenticate, authorize('ADMIN'), updateBanner);
router.delete('/:id', authenticate, authorize('ADMIN'), deleteBanner);
export default router;
