export interface FallbackProduct {
  id: string;
  name: string;
  slug: string;
  price: number;
  comparePrice?: number;
  discountPercentage?: number;
  unit: string;
  images: { url: string; alt?: string }[];
  isOrganic?: boolean;
  isFreshToday?: boolean;
  isFeatured?: boolean;
  categorySlug: string;
  rating: number;
  reviewCount: number;
  inventory: { availableStock: number };
}

export const FALLBACK_PRODUCTS: FallbackProduct[] = [
  // ─── Fresh Vegetables ───
  {
    id: 'veg-1',
    name: 'Farm Fresh Red Tomatoes',
    slug: 'farm-fresh-red-tomatoes',
    price: 32,
    comparePrice: 45,
    discountPercentage: 28,
    unit: '1 kg (approx 8-10 pcs)',
    images: [{ url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&q=80', alt: 'Fresh Tomatoes' }],
    isOrganic: true,
    isFreshToday: true,
    isFeatured: true,
    categorySlug: 'vegetables',
    rating: 4.9,
    reviewCount: 342,
    inventory: { availableStock: 48 },
  },
  {
    id: 'veg-2',
    name: 'Tender Green Bhindi (Lady Finger)',
    slug: 'tender-green-bhindi',
    price: 38,
    comparePrice: 50,
    discountPercentage: 24,
    unit: '500g',
    images: [{ url: 'https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?w=500&q=80', alt: 'Green Bhindi' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'vegetables',
    rating: 4.8,
    reviewCount: 189,
    inventory: { availableStock: 35 },
  },
  {
    id: 'veg-3',
    name: 'Nashik Red Onions (Medium)',
    slug: 'nashik-red-onions',
    price: 35,
    comparePrice: 42,
    discountPercentage: 16,
    unit: '1 kg (approx 7-9 pcs)',
    images: [{ url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=500&q=80', alt: 'Red Onions' }],
    isOrganic: false,
    isFreshToday: true,
    categorySlug: 'vegetables',
    rating: 4.7,
    reviewCount: 512,
    inventory: { availableStock: 120 },
  },
  {
    id: 'veg-4',
    name: 'New Crop Pahadi Potatoes',
    slug: 'new-crop-pahadi-potatoes',
    price: 34,
    comparePrice: 40,
    discountPercentage: 15,
    unit: '1 kg (approx 6-8 pcs)',
    images: [{ url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&q=80', alt: 'Pahadi Potatoes' }],
    isOrganic: false,
    isFreshToday: false,
    categorySlug: 'vegetables',
    rating: 4.9,
    reviewCount: 420,
    inventory: { availableStock: 90 },
  },
  {
    id: 'veg-5',
    name: 'Crisp Green Capsicum',
    slug: 'crisp-green-capsicum',
    price: 42,
    comparePrice: 55,
    discountPercentage: 23,
    unit: '500g (3-4 pcs)',
    images: [{ url: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&q=80', alt: 'Capsicum' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'vegetables',
    rating: 4.8,
    reviewCount: 164,
    inventory: { availableStock: 25 },
  },
  {
    id: 'veg-6',
    name: 'Sweet Tender Sweetcorn',
    slug: 'sweet-tender-sweetcorn',
    price: 24,
    comparePrice: 35,
    discountPercentage: 31,
    unit: '2 pcs (approx 400g)',
    images: [{ url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=500&q=80', alt: 'Sweetcorn' }],
    isOrganic: false,
    isFreshToday: true,
    categorySlug: 'vegetables',
    rating: 4.9,
    reviewCount: 230,
    inventory: { availableStock: 50 },
  },

  // ─── 100% Organic Produce ───
  {
    id: 'org-1',
    name: '100% Organic Cherry Vine Tomatoes',
    slug: 'organic-cherry-vine-tomatoes',
    price: 65,
    comparePrice: 90,
    discountPercentage: 27,
    unit: '250g punnet',
    images: [{ url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&q=80', alt: 'Organic Cherry Tomatoes' }],
    isOrganic: true,
    isFreshToday: true,
    isFeatured: true,
    categorySlug: 'organic',
    rating: 5.0,
    reviewCount: 284,
    inventory: { availableStock: 40 },
  },
  {
    id: 'org-2',
    name: 'Certified Organic Hass Avocado',
    slug: 'certified-organic-hass-avocado',
    price: 149,
    comparePrice: 199,
    discountPercentage: 25,
    unit: '2 pcs (approx 340g)',
    images: [{ url: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&q=80', alt: 'Hass Avocado' }],
    isOrganic: true,
    isFreshToday: true,
    isFeatured: true,
    categorySlug: 'organic',
    rating: 4.9,
    reviewCount: 310,
    inventory: { availableStock: 30 },
  },
  {
    id: 'org-3',
    name: 'Zero-Pesticide English Cucumber',
    slug: 'zero-pesticide-english-cucumber',
    price: 39,
    comparePrice: 50,
    discountPercentage: 22,
    unit: '500g (2-3 pcs)',
    images: [{ url: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=500&q=80', alt: 'Cucumber' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'organic',
    rating: 4.8,
    reviewCount: 145,
    inventory: { availableStock: 44 },
  },
  {
    id: 'org-4',
    name: 'Organic Tender Baby Spinach (Palak)',
    slug: 'organic-tender-baby-spinach',
    price: 38,
    comparePrice: 48,
    discountPercentage: 20,
    unit: '250g bunch',
    images: [{ url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&q=80', alt: 'Organic Palak' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'organic',
    rating: 4.9,
    reviewCount: 228,
    inventory: { availableStock: 50 },
  },
  {
    id: 'org-5',
    name: 'Organic Desi Carrots (Orange)',
    slug: 'organic-desi-carrots-orange',
    price: 45,
    comparePrice: 60,
    discountPercentage: 25,
    unit: '500g',
    images: [{ url: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&q=80', alt: 'Organic Carrots' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'organic',
    rating: 4.8,
    reviewCount: 198,
    inventory: { availableStock: 60 },
  },

  // ─── Leafy Greens & Hydroponics ───
  {
    id: 'leaf-1',
    name: 'Hydroponic Butterhead Lettuce',
    slug: 'hydroponic-butterhead-lettuce',
    price: 89,
    comparePrice: 110,
    discountPercentage: 19,
    unit: '250g head (root-on)',
    images: [{ url: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500&q=80', alt: 'Butterhead Lettuce' }],
    isOrganic: true,
    isFreshToday: true,
    isFeatured: true,
    categorySlug: 'leafy-greens',
    rating: 4.9,
    reviewCount: 177,
    inventory: { availableStock: 25 },
  },
  {
    id: 'leaf-2',
    name: 'Crisp Hydroponic Romaine Lettuce',
    slug: 'hydroponic-romaine-lettuce',
    price: 79,
    comparePrice: 95,
    discountPercentage: 16,
    unit: '250g head',
    images: [{ url: 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=500&q=80', alt: 'Romaine Lettuce' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'leafy-greens',
    rating: 4.8,
    reviewCount: 92,
    inventory: { availableStock: 20 },
  },
  {
    id: 'leaf-3',
    name: 'Fresh Italian Basil Leaves',
    slug: 'fresh-italian-basil-leaves',
    price: 35,
    comparePrice: 45,
    discountPercentage: 22,
    unit: '50g pack',
    images: [{ url: 'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?w=500&q=80', alt: 'Fresh Basil' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'leafy-greens',
    rating: 4.9,
    reviewCount: 115,
    inventory: { availableStock: 30 },
  },

  // ─── Orchard Fruits ───
  {
    id: 'fr-1',
    name: 'Himachal Royal Gala Crisp Apples',
    slug: 'himachal-royal-gala-crisp-apples',
    price: 160,
    comparePrice: 210,
    discountPercentage: 23,
    unit: '4 pcs (approx 650g)',
    images: [{ url: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&q=80', alt: 'Gala Apples' }],
    isOrganic: false,
    isFreshToday: true,
    isFeatured: true,
    categorySlug: 'fruits',
    rating: 4.9,
    reviewCount: 428,
    inventory: { availableStock: 75 },
  },
  {
    id: 'fr-2',
    name: 'Yellaki Sweet Bananas (Desi)',
    slug: 'yellaki-sweet-bananas-desi',
    price: 52,
    comparePrice: 65,
    discountPercentage: 20,
    unit: '6 pcs (approx 500g)',
    images: [{ url: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&q=80', alt: 'Yellaki Bananas' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'fruits',
    rating: 4.9,
    reviewCount: 520,
    inventory: { availableStock: 95 },
  },
  {
    id: 'fr-3',
    name: 'Imported Sweet Sun-Kissed Oranges',
    slug: 'imported-sweet-sunkissed-oranges',
    price: 125,
    comparePrice: 155,
    discountPercentage: 19,
    unit: '1 kg (4-5 pcs)',
    images: [{ url: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=500&q=80', alt: 'Oranges' }],
    isOrganic: false,
    isFreshToday: true,
    categorySlug: 'fruits',
    rating: 4.7,
    reviewCount: 210,
    inventory: { availableStock: 50 },
  },
  {
    id: 'fr-4',
    name: 'Ruby Red Pomegranate (Anaar)',
    slug: 'ruby-red-pomegranate-anaar',
    price: 145,
    comparePrice: 180,
    discountPercentage: 19,
    unit: '2 pcs (approx 500g)',
    images: [{ url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&q=80', alt: 'Pomegranate' }],
    isOrganic: false,
    isFreshToday: true,
    categorySlug: 'fruits',
    rating: 4.8,
    reviewCount: 188,
    inventory: { availableStock: 40 },
  },

  // ─── Gourmet & Exotic ───
  {
    id: 'exo-1',
    name: 'Tender Green Asparagus Spear',
    slug: 'tender-green-asparagus-spear',
    price: 149,
    comparePrice: 190,
    discountPercentage: 21,
    unit: '250g bunch',
    images: [{ url: 'https://images.unsplash.com/photo-1515471204630-e60b72958db8?w=500&q=80', alt: 'Asparagus' }],
    isOrganic: true,
    isFreshToday: true,
    isFeatured: true,
    categorySlug: 'exotic-vegetables',
    rating: 4.9,
    reviewCount: 96,
    inventory: { availableStock: 18 },
  },
  {
    id: 'exo-2',
    name: 'Exotic Trio Bell Peppers (Red, Yellow, Green)',
    slug: 'exotic-trio-bell-peppers',
    price: 129,
    comparePrice: 160,
    discountPercentage: 19,
    unit: '3 pcs (approx 450g)',
    images: [{ url: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&q=80', alt: 'Trio Peppers' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'exotic-vegetables',
    rating: 4.8,
    reviewCount: 142,
    inventory: { availableStock: 25 },
  },
  {
    id: 'exo-3',
    name: 'Fresh Green Zucchini (Courgette)',
    slug: 'fresh-green-zucchini',
    price: 69,
    comparePrice: 85,
    discountPercentage: 18,
    unit: '500g (2 pcs)',
    images: [{ url: 'https://images.unsplash.com/photo-1563205764-79ea509b3e95?w=500&q=80', alt: 'Zucchini' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'exotic-vegetables',
    rating: 4.7,
    reviewCount: 88,
    inventory: { availableStock: 22 },
  },

  // ─── Herbs & Seasonings ───
  {
    id: 'hrb-1',
    name: 'Fresh Clean Coriander (Dhaniya)',
    slug: 'fresh-clean-coriander-dhaniya',
    price: 15,
    comparePrice: 20,
    discountPercentage: 25,
    unit: '100g bunch',
    images: [{ url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&q=80', alt: 'Coriander' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'herbs-spices',
    rating: 4.9,
    reviewCount: 650,
    inventory: { availableStock: 150 },
  },
  {
    id: 'hrb-2',
    name: 'Aromatic Fresh Mint (Pudina)',
    slug: 'aromatic-fresh-mint-pudina',
    price: 18,
    comparePrice: 25,
    discountPercentage: 28,
    unit: '100g bunch',
    images: [{ url: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500&q=80', alt: 'Mint' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'herbs-spices',
    rating: 4.8,
    reviewCount: 420,
    inventory: { availableStock: 100 },
  },
  {
    id: 'hrb-3',
    name: 'Washed Indian Curry Leaves (Kadi Patta)',
    slug: 'washed-indian-curry-leaves',
    price: 12,
    comparePrice: 15,
    discountPercentage: 20,
    unit: '50g bunch',
    images: [{ url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&q=80', alt: 'Curry Leaves' }],
    isOrganic: true,
    isFreshToday: true,
    categorySlug: 'herbs-spices',
    rating: 4.9,
    reviewCount: 380,
    inventory: { availableStock: 120 },
  },
];

/**
 * Filter fallback products by category slug and filters
 */
export function getFallbackProducts(categorySlug?: string, filters?: { isOrganic?: boolean; isFreshToday?: boolean; maxPrice?: number }): FallbackProduct[] {
  let list = FALLBACK_PRODUCTS;

  if (categorySlug && categorySlug !== 'all') {
    if (categorySlug === 'organic') {
      list = list.filter(p => p.isOrganic || p.categorySlug === 'organic');
    } else {
      list = list.filter(p => p.categorySlug === categorySlug);
    }
  }

  if (filters?.isOrganic) {
    list = list.filter(p => p.isOrganic);
  }

  if (filters?.isFreshToday) {
    list = list.filter(p => p.isFreshToday);
  }

  if (filters?.maxPrice) {
    list = list.filter(p => p.price <= filters.maxPrice!);
  }

  return list;
}
